name: Build and Run Tests by Bazel
on:
  pull_request:
    types: []
  push:
    branches:
      - rwntest

jobs:
  build:
    name: "bazel-compile (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bazel build --config=remote //...
      - name: Run Tests
        run: bazel test --config=remote --nocache_test_results //...